### ISSUE TITLE
How do I insert sidenotes?

### ISSUE THREAD

**Issue by Smingvin** [studiolampblack/typographical-hugo#20]
As far as I can see it's undocumented but I see sidenotes in the demo blog.

**Comment by Smingvin** [comment]
Never mind. 

For any other confused soul out there, the syntax is:

```
{{<sidenote>}} content of your note here {{< /sidenote >}} 
```

**Comment by theramiyer** [comment]
Hello! Sorry, missed this notification.

There are two things here: Sidenotes and margin notes. I haven't implemented margin notes just yet, but for sidenotes, you might want to give them a name. Like so:

```
{{< sidenote "mynote" >}}content of your note here{{ /sidenote }}
```

This way, the toggle works best in mobile layouts. I'll add this to the documentation. Thanks for pointing it out!
